version: "3.7"
services:
  jupyter-lab:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_TOKEN=codeop
    volumes:
      - ./nbs:/home/jovyan/work
    ports:
      - 8888:8888
